app:
  baseurl: "dev.auto-mall.ro"
  test:
    db:
      name: "test"
  db:
    user: "dev"
    pass: "siana1316"
    name: "automall"
    host: "dev.auto-mall.ro"
#    host: "65.108.215.227"
service:
  sessionstarter:
    http:
      port: "3223"
  backend:
    http:
      port: "8080"
smq:
  http:
    port: "3113"
  url: "dev.auto-mall.ro"
  jobs:
    topic:
      name: "jobs"
  results:
    topic:
      name: "results"
mock:
  http:
    port: "4114"
