name: car-mall
services:
  backend_logs:
    build:
      context: ./
      dockerfile: cmd/backend-logs/Dockerfile
    ports:
      - "8088:8088"
    environment:
      - APP_BASE_URL=dev.auto-mall.ro
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_LOGS=logs
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=dev.auto-mall.ro
      - BACKEND_HTTP_PORT=8080
      - APP_BACKENDLOGS_PORT=8088
    profiles:
      - prod
  backend:
    build:
      context: ./
      dockerfile: cmd/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_BASE_URL=dev.auto-mall.ro
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=dev.auto-mall.ro
      - BACKEND_HTTP_PORT=8080
    profiles:
      - prod
  sessionstarter:
    build:
      context: ./
      dockerfile: cmd/sessionstarter/Dockerfile
    ports:
      - "3223:3223"
    environment:
      - SESSIONSTARTER_HTTP_PORT=3223
      - APP_BASE_URL=dev.auto-mall.ro
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=dev.auto-mall.ro
      - SMQ_HTTP_PORT=3113
      - SMQ_JOBS_TOPIC_NAME="jobs"
    profiles:
      - prod
  chromium:
    container_name: "rod-chromium"
    ports:
      - "7317:7317"
    image: "ghcr.io/go-rod/rod"
    profiles:
      - localdev
      - prod
    networks:
      - localdev
  pagescraper:
    build:
      context: ./
      dockerfile: cmd/pagescraper/Dockerfile
    ports:
      - "3993:3993"
    environment:
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_LOGS=logs
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=dev.auto-mall.ro
      - SMQ_HTTP_PORT=3113
      - SMQ_JOBS_TOPIC_NAME=jobs
      - SMQ_RESULTS_TOPIC_NAME=results
      - PAGESCRAPER_USE_DOCKER_ROD=true
      - PAGESCRAPER_DOCKER_CONTAINER_URL=http://dev.auto-mall.ro:7317
    profiles:
      - prod
      - localdev
    networks:
      - localdev
  resultsconsumer:
    build:
      context: ./
      dockerfile: cmd/resultsconsumer/Dockerfile
    ports:
      - "4224:4224"
    environment:
      - APP_BASE_URL=dev.auto-mall.ro
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_VEHICLES=vehicles
      - APP_DB_LOGS=logs
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=smq-smq-1
      - SMQ_HTTP_PORT=3113
      - SMQ_JOBS_TOPIC_NAME=jobs
      - SMQ_RESULTS_TOPIC_NAME=results
    profiles:
      - prod
#  envtest:
#    build:
#      context: ./
#      dockerfile: cmd/envtest/Dockerfile
##    profiles:
##         ["dev", "prod"]
##    environment:
##        - TEST_VAR=${TEST_VAR}
#    env_file:
#      - development.env
networks:
  localdev: