name: auto-mall-dev
services:
  envtest:
    build:
      context: ./
      dockerfile: cmd/envtest/Dockerfile
#    environment:
#      - TEST_VAR=${TEST_VAR}
    env_file:
      - dev.env
  resultsconsumer:
    build:
      context: ./
      dockerfile: cmd/resultsconsumer/Dockerfile
    ports:
      - "4224:4224"
    environment:
      - APP_BASE_URL=dev.auto-mall.ro
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_VEHICLES=vehicles
      - APP_DB_LOGS=logs
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=smq-smq-1
      - SMQ_HTTP_PORT=3113
      - SMQ_JOBS_TOPIC_NAME=jobs
      - SMQ_RESULTS_TOPIC_NAME=results
    profiles:
      - prod
    networks:
      - automall-dev
  pagescraper:
    build:
      context: ./
      dockerfile: cmd/pagescraper/Dockerfile
    ports:
      - "3993:3993"
    environment:
      - APP_DB_USER=dev
      - APP_DB_PASS=siana1316
      - APP_DB_NAME=automall
      - APP_DB_LOGS=logs
      - APP_DB_HOST=dev.auto-mall.ro
      - SMQ_URL=127.0.0.1
      - SMQ_HTTP_PORT=3113
      - SMQ_JOBS_TOPIC_NAME=jobs
      - SMQ_RESULTS_TOPIC_NAME=results
    networks:
      - automall-dev
networks:
  automall-dev:
    driver: bridge